name: My First Workflow

on: 
  push:
    branches:
      - master 

jobs:
  say-hello
    runs-on: ubuntu-latest

    steps:
      - name: say hello
        run: echo "Hello! my workflow is running!"
      
      - name: Show the date
        run: date
      
      - name: List files
        run: ls -la
    