name: About me

on: 
  push:
    branches:
      - master

jobs:
  say-hello:
    runs-on: ubuntu-latest
    
    steps:
      - name: My name
        run: echo "My name is Ashith"

      - name: Today is
        run: date +%A

      - name: Fun fact
        run: echo "I'm learning CI/CD!"
 